name: Deploy Site
on:
  push:
    branches:
      - "*"
jobs:
  Upload to CloudFlare Pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Publish site content
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: whoami
