name: Deploy Site
on:
  push:
    branches:
      - "*"
jobs:
  upload-to-cloudflare-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Publish site content
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name brintonium-site site/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
